"""CUDA execution suite for the ``AtomicAccumulateNode``.

A thin binding of the backend-agnostic scenarios in ``_atomic_accumulate_impl``
to the CUDA backend. Every test is generated by :func:`register` and carries the
module-level ``cuda`` marker.
"""

import pytest

import _atomic_accumulate_impl as aa

pytestmark = pytest.mark.cuda()

aa.register(globals(), aa.CUDA_BACKEND)
