"""ROCm execution suite for the ``AtomicAccumulateNode``.

A thin binding of the backend-agnostic scenarios in ``_atomic_accumulate_impl``
to the ROCm backend. Every test is generated by :func:`register` and carries the
module-level ``rocm`` marker.
"""

import pytest

import _atomic_accumulate_impl as aa

pytestmark = pytest.mark.rocm()

aa.register(globals(), aa.ROCM_BACKEND)
